language: c
os:
    - linux
    - osx
before_install:
    - sudo apt-get install python3
install: 
    - ./configure build
    - ./configure pylib
script: 
    - ./build/bin/examples/sin_test
    - ./build/bin/examples/xor_test
    - python3 examples/pytest.py
compiler:
    - clang
    - gcc

