language: 
    - c
    - python
os:
    - linux
python:
    - "3.5"
    - "3.5-dev"
    - "3.6"
before_install:
    - sudo apt-get install python3
    - sudo apt-get install python3-dev
install: 
    - ./configure build
script: 
    - ./build/bin/examples/sin_test
    - ./build/bin/examples/xor_test
    - python3 examples/pytest.py
compiler:
    - clang
    - gcc

