language: c
os:
    - linux
before_install:
    - sudo apt-get install python3.5
    - sudo apt-get install python3.5-dev
install: 
    - ./configure build
script: 
    - ./build/bin/examples/sin_test
    - ./build/bin/examples/xor_test
    - python3 examples/pytest.py
compiler:
    - clang
    - gcc

